In [1]:
import pandas as pd
pd.set_option("display.max_columns", 100)

In [2]:
hr = pd.read_excel("hr.xlsx")

In [3]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1205 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1205 non-null   float64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(1), int64(25), object(9)
memory usage: 402.1+ KB

In [4]:
hr.isnull().sum()

Age                           0
Attrition                   265
BusinessTravel                0
DailyRate                     0
Department                    0
DistanceFromHome              0
Education                     0
EducationField                0
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction               0
MaritalStatus                 0
MonthlyIncome               265
MonthlyRate                   0
NumCompaniesWorked            0
Over18                        0
OverTime                      0
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel              0
TotalWorkingYears             0
TrainingTimesLastYear         0
WorkLifeBalance               0
YearsAtCompany                0
YearsInCurrentRole            0
YearsSinceLastPromotion       0
YearsWithCurrManager          0
dtype: int64

In [5]:
hr.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993.0,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130.0,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090.0,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909.0,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468.0,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [6]:
hr.MaritalStatus.nunique()

3

In [7]:
hr.MaritalStatus.unique()

array(['Single', 'Married', 'Divorced'], dtype=object)

In [8]:
hr.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1205.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,6523.930290,14313.103401,2.693197,15.209524,3.153741,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,4756.215086,7117.786044,2.498009,3.659938,0.360824,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1051.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,2897.000000,8047.000000,1.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,4936.000000,14235.500000,2.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,8237.000000,20461.500000,4.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [9]:
hr.MaritalStatus.value_counts()

Married     673
Single      470
Divorced    327
Name: MaritalStatus, dtype: int64

# regression

In [18]:
miss = hr.isnull().sum()
miss[miss>0]

Attrition        265
MonthlyIncome    265
dtype: int64

In [19]:
data = hr.copy()
del data["Attrition"]

In [17]:
data.isnull().sum()

0

In [20]:
missing = data[data["MonthlyIncome"].isnull()]
filled = data[data["MonthlyIncome"].notnull()]

In [21]:
missing.shape, filled.shape

((265, 34), (1205, 34))

In [22]:
filled.corr()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,0.017555,0.003074,0.215022,NaN,-0.030078,0.017511,0.010490,0.026380,0.524683,-0.002142,0.504376,0.030861,0.281257,-0.007668,-0.017728,0.054784,NaN,0.007166,0.678289,-0.007230,-0.032737,0.323413,0.209129,0.221807,0.214771
DailyRate,0.017555,1.000000,0.005963,-0.014068,NaN,-0.047483,0.035487,0.015392,0.027986,0.002527,0.024612,0.009597,-0.034968,0.038203,0.029811,0.000068,-0.010120,NaN,0.052685,0.005077,-0.019137,-0.058334,-0.043150,0.010441,-0.034099,-0.028570
DistanceFromHome,0.003074,0.005963,1.000000,0.035379,NaN,0.020763,-0.030170,0.027519,0.033623,0.006032,-0.005838,-0.009285,0.045875,-0.016143,0.039423,0.028285,0.013337,NaN,0.062579,0.017436,-0.033804,-0.016886,0.007022,0.023506,0.014140,0.014597
Education,0.215022,-0.014068,0.035379,1.000000,NaN,0.045023,-0.024908,-0.006329,0.066902,0.103864,-0.014474,0.095758,-0.029582,0.125083,-0.019455,-0.029513,-0.015992,NaN,-0.004353,0.157465,-0.016219,0.012274,0.079556,0.067478,0.062813,0.081593
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeNumber,-0.030078,-0.047483,0.020763,0.045023,NaN,1.000000,0.028064,-0.004309,0.006398,-0.019065,-0.041587,-0.015974,0.008877,-0.017408,-0.024460,-0.046639,-0.085285,NaN,0.044376,-0.022418,0.016559,0.014841,-0.010650,-0.011192,-0.003753,-0.012552
EnvironmentSatisfaction,0.017511,0.035487,-0.030170,-0.024908,NaN,0.028064,1.000000,-0.046590,-0.013060,-0.003212,0.000359,-0.005332,0.031333,0.006870,-0.046696,-0.041666,-0.001946,NaN,0.003917,-0.004758,-0.015246,0.036916,0.000836,0.023155,0.016795,-0.010579
HourlyRate,0.010490,0.015392,0.027519,-0.006329,NaN,-0.004309,-0.046590,1.000000,0.041263,-0.019858,-0.058157,-0.010333,-0.026831,0.026877,-0.002272,0.007760,-0.001814,NaN,0.038181,-0.008770,-0.010727,-0.004388,-0.032050,-0.041045,-0.033828,-0.034277
JobInvolvement,0.026380,0.027986,0.033623,0.066902,NaN,0.006398,-0.013060,0.041263,1.000000,-0.014145,-0.017064,-0.019477,-0.026837,0.019130,-0.005307,-0.019707,0.027719,NaN,0.039984,-0.003143,-0.019101,-0.015039,-0.011509,0.014308,-0.008718,0.034495
JobLevel,0.524683,0.002527,0.006032,0.103864,NaN,-0.019065,-0.003212,-0.019858,-0.014145,1.000000,-0.013625,0.951287,0.031863,0.135199,-0.029989,-0.022727,0.035728,NaN,0.001562,0.791560,-0.003407,0.033094,0.547500,0.390848,0.364095,0.388201
JobSatisfaction,-0.002142,0.024612,-0.005838,-0.014474,NaN,-0.041587,0.000359,-0.058157,-0.017064,-0.013625,1.000000,-0.013752,-0.003375,-0.052141,0.050163,0.025462,-0.026170,NaN,0.020174,-0.021094,-0.019097,-0.015906,-0.009360,-0.009423,-0.033279,-0.030648
MonthlyIncome,0.504376,0.009597,-0.009285,0.095758,NaN,-0.015974,-0.005332,-0.010333,-0.019477,0.951287,-0.013752,1.000000,0.023419,0.138344,-0.023454,-0.012966,0.035059,NaN,-0.002759,0.780438,-0.006785,0.020497,0.527649,0.365401,0.350071,0.357689
MonthlyRate,0.030861,-0.034968,0.045875,-0.029582,NaN,0.008877,0.031333,-0.026831,-0.026837,0.031863,-0.003375,0.023419,1.000000,0.022356,-0.001128,-0.003830,-0.015880,NaN,-0.031165,0.024765,0.011933,0.008292,-0.020509,-0.013080,0.000653,-0.043892
NumCompaniesWorked,0.281257,0.038203,-0.016143,0.125083,NaN,-0.017408,0.006870,0.026877,0.019130,0.135199,-0.052141,0.138344,0.022356,1.000000,-0.021536,-0.020332,0.052691,NaN,-0.005377,0.229580,-0.067244,-0.031370,-0.128953,-0.099356,-0.047134,-0.113045
PercentSalaryHike,-0.007668,0.029811,0.039423,-0.019455,NaN,-0.024460,-0.046696,-0.002272,-0.005307,-0.029989,0.050163,-0.023454,-0.001128,-0.021536,1.000000,0.765651,-0.052272,NaN,-0.013963,-0.026565,-0.001768,-0.006855,-0.035878,-0.002459,-0.019454,-0.012685
PerformanceRating,-0.017728,0.000068,0.028285,-0.029513,NaN,-0.046639,-0.041666,0.007760,-0.019707,-0.022727,0.025462,-0.012966,-0.003830,-0.020332,0.765651,1.000000,-0.034372,NaN,-0.021073,-0.000419,-0.001810,-0.005045,-0.001171,0.021699,0.020794,0.009999
RelationshipSatisfaction,0.054784,-0.010120,0.013337,-0.015992,NaN,-0.085285,-0.001946,-0.001814,0.027719,0.035728,-0.026170,0.035059,-0.015880,0.052691,-0.052272,-0.034372,1.000000,NaN,-0.058883,0.037737,0.004856,0.003847,0.040114,-0.001715,0.040362,0.009941
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,0.007166,0.052685,0.062579,-0.004353,NaN,0.044376,0.003917,0.038181,0.039984,0.001562,0.020174,-0.002759,-0.031165,-0.005377,-0.013963,-0.021073,-0.058883,NaN,1.000000,-0.019810,0.011430,-0.010981,0.004731,0.042351,0.020933,0.033556
TotalWorkingYears,0.678289,0.005077,0.017436,0.157465,NaN,-0.022418,-0.004758,-0.008770,-0.003143,0.791560,-0.021094,0.780438,0.024765,0.229580,-0.026565,-0.000419,0.037737,NaN,-0.019810,1.000000,-0.019894,-0.007726,0.639866,0.459335,0.412526,0.468521
TrainingTimesLastYear,-0.007230,-0.019137,-0.033804,-0.016219,NaN,0.016559,-0.015246,-0.010727,-0.019101,-0.003407,-0.019097,-0.006785,0.011933,-0.067244,-0.001768,-0.001810,0.004856,NaN,0.011430,-0.019894,1.000000,0.032415,0.009222,-0.007024,-0.002168,0.003276
WorkLifeBalance,-0.032737,-0.058334,-0.016886,0.012274,NaN,0.014841,0.036916,-0.004388,-0.015039,0.033094,-0.015906,0.020497,0.008292,-0.031370,-0.006855,-0.005045,0.003847,NaN,-0.010981,-0.007726,0.032415,1.000000,0.024683,0.058366,0.007052,0.026805
YearsAtCompany,0.323413,-0.043150,0.007022,0.079556,NaN,-0.010650,0.000836,-0.032050,-0.011509,0.547500,-0.009360,0.527649,-0.020509,-0.128953,-0.035878,-0.001171,0.040114,NaN,0.004731,0.639866,0.009222,0.024683,1.000000,0.750858,0.621920,0.764028
YearsInCurrentRole,0.209129,0.010441,0.023506,0.067478,NaN,-0.011192,0.023155,-0.041045,0.014308,0.390848,-0.009423,0.365401,-0.013080,-0.099356,-0.002459,0.021699,-0.001715,NaN,0.042351,0.459335,-0.007024,0.058366,0.750858,1.000000,0.553056,0.717107
YearsSinceLastPromotion,0.221807,-0.034099,0.014140,0.062813,NaN,-0.003753,0.016795,-0.033828,-0.008718,0.364095,-0.033279,0.350071,0.000653,-0.047134,-0.019454,0.020794,0.040362,NaN,0.020933,0.412526,-0.002168,0.007052,0.621920,0.553056,1.000000,0.512828
YearsWithCurrManager,0.214771,-0.028570,0.014597,0.081593,NaN,-0.012552,-0.010579,-0.034277,0.034495,0.388201,-0.030648,0.357689,-0.043892,-0.113045,-0.012685,0.009999,0.009941,NaN,0.033556,0.468521,0.003276,0.026805,0.764028,0.717107,0.512828,1.000000

In [23]:
abs(filled.corr()["MonthlyIncome"]).sort_values(ascending=False)

MonthlyIncome               1.000000
JobLevel                    0.951287
TotalWorkingYears           0.780438
YearsAtCompany              0.527649
Age                         0.504376
YearsInCurrentRole          0.365401
YearsWithCurrManager        0.357689
YearsSinceLastPromotion     0.350071
NumCompaniesWorked          0.138344
Education                   0.095758
RelationshipSatisfaction    0.035059
PercentSalaryHike           0.023454
MonthlyRate                 0.023419
WorkLifeBalance             0.020497
JobInvolvement              0.019477
EmployeeNumber              0.015974
JobSatisfaction             0.013752
PerformanceRating           0.012966
HourlyRate                  0.010333
DailyRate                   0.009597
DistanceFromHome            0.009285
TrainingTimesLastYear       0.006785
EnvironmentSatisfaction     0.005332
StockOptionLevel            0.002759
EmployeeCount                    NaN
StandardHours                    NaN
Name: MonthlyIncome, dtype: float64

In [24]:
from scipy import stats
est = stats.linregress(x=filled["TotalWorkingYears"], y=filled["MonthlyIncome"])